package observer;

import model.Order;
import simulation.StaffStatus;

import java.util.List;
import java.util.Map;

/**
 * Observer interface used by the GUI View to receive updates from the
 * SimulationModel (MVC pattern).
 *
 * <p>Notifications are always delivered on the Swing Event Dispatch Thread,
 * so implementations may update UI components directly.</p>
 */
public interface ModelObserver {

    /**
     * Called when the simulation state changes (queue or staff status).
     *
     * @param queue         current snapshot of the customer queue
     *                      (front of queue at index 0)
     * @param staffStatuses map from staff name to their current status;
     *                      iteration order is insertion order
     */
    void onModelUpdated(List<Order> queue, Map<String, StaffStatus> staffStatuses);

    /**
     * Called once, when all orders have been processed and the simulation ends.
     *
     * @param finalReport the plain-text sales report generated by the Manager
     */
    void onSimulationComplete(String finalReport);
}
